on:
  push:
    paths:
      - '**.lua' # Run if pushed commits include a change to a Lua (.lua) file.
      - 'extension.xml' # Run if pushed commits include a change to extension definition file.
  pull_request:
    # Only run if pull request includes a change to a Lua (.lua) file.
    paths:
      - '**.lua' # Run if pushed commits include a change to a Lua (.lua) file.
      - 'extension.xml' # Run if pushed commits include a change to extension definition file.
  schedule:
    - cron: 0 0 * * *
  workflow_dispatch:

name: Run Luacheck on Default Branch

jobs:
  inherit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.repository.default_branch }}

      - name: Inherit other repos from extension.xml
        id: inheritrepos
        uses: mavrosxristoforos/get-xml-info@1.1.0
        with:
          xml-file: 'extension.xml'
          xpath: '//properties//luacheck//repo'

      - id: outerquotes
        uses: ashley-taylor/regex-property-action@1.2
        with:
          value: ${{ steps.inheritrepos.outputs.info }}
          regex: '(.+)'
          replacement: '["$1"]'

      - id: innerquotes
        uses: ashley-taylor/regex-property-action@1.2
        with:
          value: ${{ steps.outerquotes.outputs.value }}
          regex: ','
          replacement: '","'
      - id: generate-matrix
        run: echo "::set-output name=repos::${{ steps.innerquotes.outputs.value }}"

    outputs:
      repos: ${{ steps.generate-matrix.outputs.repos }}

  generateconfig:
    name: Clone FG-Unofficial-Developers-Guild/2E
    runs-on: ubuntu-latest
    needs: inherit
#    strategy:
#      matrix:
#          package: ${{ fromJson(needs.inherit.outputs.repos) }}
    steps:
      - id: generate-matrix
        run: echo ${{ needs.inherit.outputs.repos }}
#      - uses: actions/checkout@v3
#        with:
#          repository: FG-Unofficial-Developers-Guild/2E
#          path: .fg/rulesets/DND2E
#          token: ${{ secrets.ACTIONS }}
#
#  luacheck:
#    runs-on: ubuntu-latest
#    steps:
#      - name: Checkout repo
#        uses: actions/checkout@v3
#        with:
#          ref: ${{ github.event.repository.default_branch }}
#
#      - name: Install Lua/LuaJIT
#        uses: leafo/gh-actions-lua@v9
#        with:
#          luaVersion: 5.1
#
#      # Process extension code
#      - name: Running luacheck
#        uses: nebularg/actions-luacheck@v1
#        with:
#          files: '.'
#          config: https://raw.githubusercontent.com/bmos/FG-luacheck/main/.luacheckrc
#          args: '--no-color --exclude-files .install/*'
#          annotate: 'warning'
#
